OCA/oca-github-bot

clabot.py

[FIX] don't check CLA for translations

---

src/oca_github_bot/github.py
src/oca_github_bot/tasks/main_branch_bot.py
tests/conftest.py
tests/test_git_push_if_needed.py

retry task in case of non-fast-forward push attempt

---

src/oca_github_bot/tasks/main_branch_bot.py

So we have a chance to see it in Sentry.
Closes #11

Capture output of main subprocess calls

---

src/oca_github_bot/manifest.py
tests/conftest.py
tests/test_manifest.py

Add manifest version handling functions

---

clabot.py

and don't notify about them multiple time
closes #29

Cache the PR's committers without a github login

---

.gitignore
src/oca_github_bot/manifest.py
tests/test_manifest.py

The test change shows what this fix means.

[FIX] bump_version: reset minor digits when updating major digits

---

Dockerfile
README.rst
src/oca_github_bot/tasks/main_branch_bot.py

[ADD] main_branch_bot: _gen_addons_icon

---

README.rst
src/oca_github_bot/commands.py
src/oca_github_bot/github.py
src/oca_github_bot/manifest.py
src/oca_github_bot/tasks/merge_bot.py
src/oca_github_bot/version_branch.py
src/oca_github_bot/webhooks/__init__.py
src/oca_github_bot/webhooks/on_check_suite.py
src/oca_github_bot/webhooks/on_command.py
src/oca_github_bot/webhooks/on_pr_review_comment.py
tests/test_commands.py
tests/test_git_get_head_sha.py
tests/test_manifest.py
tests/test_on_check_suite.py
tests/test_on_command.py
tests/test_version_branch.py

merge command

---

README.rst
environment.sample
src/oca_github_bot/config.py
src/oca_github_bot/tasks/delete_branch.py
src/oca_github_bot/tasks/main_branch_bot.py
src/oca_github_bot/tasks/merge_bot.py
src/oca_github_bot/tasks/tag_approved.py
src/oca_github_bot/tasks/tag_ready_to_merge.py
tests/test_switchable.py

Allows to specify the list of tasks performed by the bot from config env

---

HISTORY.rst
src/oca_github_bot/commands.py
tests/test_commands.py

improve command parser

---

HISTORY.rst
src/oca_github_bot/build_wheels.py
src/oca_github_bot/github.py
src/oca_github_bot/tasks/main_branch_bot.py

for better output capture (unicode instead of binary),
and better display of errors in merge bot

Call external tools with universal_newlines=True

---

README.rst

Just putting my correct name 😅

[FIX] readme: contributor name

---

src/oca_github_bot/tasks/merge_bot.py

Closes #68 
Instead of rebasing the PR onto the target branch, create a merge commit to the main branch, and push it to the main branch if green.
So the first phase
- creates the merge bot branch from the target branch
- creates the merge commit of the PR to the target branch
- pushes the merge bot branch
- await test results
And the second phase
- checks if the target branch is an ancestor of the merge bot branch (else retry the first phase)
- bump version
- push the merge bot branch to the target branch

merge bot: change merge strategy to "merge"

---

src/oca_github_bot/tasks/merge_bot.py

If a PR set `'installable' : False` for an addon, the merge_bot fails. Indeed, the process will try to build the wheel for this no more installable addon.

merge_bot: Bumpversion and build wheels of installable addons only

---

README.rst
src/oca_github_bot/github.py
src/oca_github_bot/tasks/main_branch_bot.py
src/oca_github_bot/tasks/merge_bot.py

temporary_clone yields directory

---

src/oca_github_bot/build_wheels.py
src/oca_github_bot/github.py
src/oca_github_bot/manifest.py
src/oca_github_bot/process.py
src/oca_github_bot/tasks/main_branch_bot.py
src/oca_github_bot/tasks/merge_bot.py

- log errors for visibility in sentry
- enforce passing cwd

Refactor subprocess calls

---

src/oca_github_bot/commands.py
tests/test_commands.py

exclude comments from matched commands + test

---

src/oca_github_bot/tasks/mention_maintainer.py
tests/test_mention_maintainer.py

Do not mention maintainer if is the PR opener

---

src/oca_github_bot/tasks/merge_bot.py

Add merging label while merging a PR

---

README.rst
environment.sample
newsfragments/112.feature
src/oca_github_bot/config.py
tests/test_switchable.py

Add ``BOT_TASKS_DISABLED`` that allows to disable only a (or many) given task(s).
Original PR #109
CC : @sbidoul

Add bot tasks disabled

---

Dockerfile

I reduced the image size by performing a better cleanup (gained ~30MB),
used the 'Linux way' of installing 3th party apps, -> the /opts folder
used the 'Elegant way' of installing python packages to their corresponding venvs.

Modified the docker file.

---

environment.sample
newsfragments/127.feature
src/oca_github_bot/config.py
src/oca_github_bot/cron.py

Hi, Proposing a trivial PR to have the possibility to use a bot for multiple organizations. (I'm currently using it for two organizations).
kind regards.

[IMP] possibility to set multiple github organizations in GITHUB_ORG arg

---

src/oca_github_bot/tasks/mention_maintainer.py
tests/test_mention_maintainer.py

Fix last part of #88: 
> The PR is adding the maintainer, but it's not yet added, so it shouldn't warn.

Only mention maintainers existing before the PR

---

environment.sample
src/oca_github_bot/config.py
src/oca_github_bot/tasks/mention_maintainer.py
tests/test_mention_maintainer.py

See https://github.com/OCA/oca-github-bot/issues/93

Add "adopt a module" message

---

README.rst
environment.sample
newsfragments/130.feature
src/oca_github_bot/config.py
src/oca_github_bot/tasks/mention_maintainer.py
tests/common.py
tests/test_mention_maintainer.py

Mostly, put the full mention in the config variable as it is more flexible.

Tweak the "adopt an addon" mechanism

---

docker-compose.yml
requirements.txt

Upgrade flower for celery 5 compatibility

---

src/oca_github_bot/tasks/migration_issue_bot.py

We need to pass the GH repo, not the repo name.
@Tecnativa

[FIX] migration_issue_bot: Handle GH repo

---

newsfragments/182.bugfix
src/oca_github_bot/webhooks/on_command.py
src/oca_github_bot/webhooks/on_pr_review.py

Test locally with ngrok. Seems working.
Fix #49
CC : @pedrobaeza, @sbidoul, @Yajo

[IMP] consider comment from PR reviews

---

src/oca_github_bot/config.py

trivial PR.
explicit command ``ocabot migration``
see : https://github.com/OCA/product-attribute/pull/1083#issuecomment-1137309813
regards.
CC : @sbidoul

[IMP] add 'migration' in the OCABOT_USAGE.

---

src/oca_github_bot/config.py

For the time being, comment is bad displayed.
see : 
https://github.com/commown/commown-odoo-addons/pull/84#issuecomment-1195328603

[FIX] add new line at end of OCABOT_USAGE line

---

newsfragments/244.bugfix
src/oca_github_bot/tasks/merge_bot.py
src/oca_github_bot/tasks/rebase_bot.py
src/oca_github_bot/utils.py
tests/test_utils.py

Fix issue with error reporting

---

src/oca_github_bot/manifest.py

https://github.com/OCA/l10n-iran/pull/35/files#r1421435363

Fix rendering of OdooSeriesNotDtected exceptions

---

Dockerfile

Include https://github.com/OCA/maintainer-tools/pull/596, notably

Upgrade maintainer-tools

---

newsfragments/277.feature
src/oca_github_bot/tasks/main_branch_bot.py

Avoid creating useless jobs for forks.

Skip forks early in main branch bot

---

src/oca_github_bot/tasks/main_branch_bot.py

Bug was introduced in https://github.com/OCA/oca-github-bot/commit/0525c4663976b947fa4892ea9ffa834fff51b5c0

Fix regression in main_branch_bot_all_repos
