OCA/oca-github-bot

- environment.sample
this will make it simpler for people to spin up a testing instance I think
> [FIX] make environment.sample work for docker out of the box

- README.rst
- src/oca_github_bot/cron.py
- src/oca_github_bot/github.py
- src/oca_github_bot/tasks/__init__.py
- src/oca_github_bot/tasks/tag_approved.py
- src/oca_github_bot/tasks/tag_ready_to_merge.py
- src/oca_github_bot/webhooks/__init__.py
- src/oca_github_bot/webhooks/on_pr_review.py
Extracted from https://github.com/OCA/maintainer-tools/pull/346
TODO
> [ADD] task to set ready to merge label

- environment.sample
- src/oca_github_bot/config.py
- src/oca_github_bot/cron.py
- src/oca_github_bot/tasks/main_branch_bot.py
Allows to specify another github organisation into the confirguration. The goal is to allow the reuse of this bot framework for others organisations.
> Takes the github organisation name from config (default OCA)

- README.rst
- src/oca_github_bot/tasks/__init__.py
- src/oca_github_bot/tasks/tag_needs_review.py
- src/oca_github_bot/webhooks/__init__.py
- src/oca_github_bot/webhooks/on_pr_green_label_needs_review.py
- tests/test_on_pr_green_label_needs_review.py
This PR adds a method that listens to the `check_suite` webhooks triggered when the CI tests finish in a PR and adds the `needs review` label if the tests were successful and the PR's title doesn't start with `WIP:` (case insensitive). 
If another commit is pushed to the PR and the tests fail, the label is removed.
closes https://github.com/OCA/oca-github-bot/issues/20
> [ADD] master: needs review label to green pull requests

- README.rst
source: https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
> allexport instead of exportall

- environment.sample
- src/oca_github_bot/tasks/__init__.py
- src/oca_github_bot/tasks/mention_maintainer.py
- src/oca_github_bot/webhooks/__init__.py
- src/oca_github_bot/webhooks/on_pr_open_mention_maintainer.py
- tests/common.py
- tests/test_mention_maintainer.py
> Mention maintainer when his module is modified

- src/oca_github_bot/manifest.py
Simulating a merge instead of a rebase
is more robust. In some situations a rebase
will not work where a merge would work.
> Improve git_get_modified_addons

- src/oca_github_bot/tasks/mention_maintainer.py
If the the Pull Request touches several modules sharing the same maintainer, it would repeat mentions.
This change ensures that each person is mentioned only once.
Example in the wild: https://github.com/OCA/l10n-chile/pull/46#issuecomment-551707048
> [FIX] Don't duplicate maintainer mentions

- HISTORY.rst
- src/oca_github_bot/build_wheels.py
Typical example: `server_environment_file_sample`
> Do not fail on twine check if an addon has no setup.py

- environment.sample
- newsfragments/103.feature
- src/oca_github_bot/config.py
- src/oca_github_bot/process.py
- src/oca_github_bot/tasks/main_branch_bot.py
WIP.
Add configuration options in environment file
> [ADD] extra arguments for 3 commands oca-gen-addons-table, oca-gen-addon-readme, oca-gen-addon-icon

- environment.sample
- newsfragments/107.feature
- src/oca_github_bot/config.py
- src/oca_github_bot/tasks/tag_approved.py
- src/oca_github_bot/tasks/tag_ready_to_merge.py
For the time being, APPROVALS_REQUIRED is hardcoded with the value 2. 
With that PR, it is configurable. 
Note : It is not the perfect design, as the approvals number is dynamic, in the real (OCA) life, and depends on the state of the modules. (stable / Beta / etc...) but it is a little step forward. 
Make also MIN_PR_AGE configurable.
> [IMP] make APPROVALS_REQUIRED configurable

- Dockerfile
- README.rst
- environment.sample
- newsfragments/106.feature
- src/oca_github_bot/tasks/merge_bot.py
This PR makes the "ocabot merge" command update `HISTORY.rst` from fragments in `readme/newsfragment` using a [thin oca specific wrapper](https://github.com/OCA/maintainer-tools/pull/432) for [towncrier](https://pypi.org/project/towncrier/).
> ocabot merge: update HISTORY.rst, using oca-towncrier

- environment.sample
- newsfragments/111.feature
- src/oca_github_bot/config.py
GITHUB_STATUS_IGNORED and GITHUB_CHECK_SUITES_IGNORED was hardcoded in config.py file.
with that PR, it is possible to configure in the ``environment`` file.
See original PR : #109
CC : @sbidoul
> Imp make dynamic GitHub ignored

- newsfragments/115.feature
- requirements.txt
- src/oca_github_bot/config.py
The check-suites GitHub api-call started reporting Dependabot in queued state, preventing merges.
It should be safe to ignore it by default.
> Ignore Dependabot in check-suite

- .travis.yml
- Dockerfile
- newsfragments/118.bugfix
Update maintainer-tools to get the latest `oca-gen-addon-tables`. It fixes a regression where the main branch operations were failing when `README.md` is absent.
> Dockerfile: refresh maintainer tools

- newsfragments/123.feature
- src/oca_github_bot/tasks/merge_bot.py
This exception was probably done with the goal of saving space,
but for migration PRs where people use ocabot merge nobump,
we want to publish too.
> [IMP] merge: publish wheels also in nobump mode

- newsfragments/141.feature
- src/oca_github_bot/tasks/merge_bot.py
Previously, there was a hack to ignore Travis check suites when the old style travis status was present.
Then we had to ignore Dependabot which was reporting a check suite that never completed.
Now, on repos that have no .travis.yml but where travis is configured organization-wide, we have Travis reporting a check suite that never completes. :/
So this is an attempt to better handle all this by ignoring check suites that have no check runs.
Also, improve logging in this area.
Why it is so hard to detect a green build... I may miss something obvious... or not.
> Ignore check suites that have no check runs

- .isort.cfg
- README.rst
- environment.sample
- requirements.txt
- setup.py
- src/oca_github_bot/build_wheels.py
- src/oca_github_bot/config.py
- src/oca_github_bot/process.py
- src/oca_github_bot/pypi.py
- src/oca_github_bot/tasks/main_branch_bot.py
- src/oca_github_bot/tasks/merge_bot.py
- tests/cassettes/test_exists_on_index[not_a_pkg-1.0-py3-none-any.whl-False].yaml
- tests/cassettes/test_exists_on_index[pip-20.4-py3-none-any.whl-False].yaml
- tests/cassettes/test_exists_on_index[pip-21.0.1-py3-none-any.whl-True].yaml
- tests/test_build_wheels.py
- tests/test_pypi.py
The bot was capable of publishing wheels to a PEP 503 compatible directory structure.
This PR allows
- publishing to a real package index via twine
- allow multiple publication targets
This will simplify the OCA infrastructured by removing the pypi publisher cron, and allow other organizations using this bot to easily publish to their own index.
closes #16
> pypi uploader

- README.rst
- environment.sample
- src/oca_github_bot/commands.py
- src/oca_github_bot/config.py
- src/oca_github_bot/manifest.py
- src/oca_github_bot/tasks/merge_bot.py
- src/oca_github_bot/tasks/rebase_bot.py
- tests/test_commands.py
- tests/test_merge_bot.py
New command. I hope it will be useful.
> [ADD] rebase_bot

- src/oca_github_bot/pypi.py
So the command argument is stable and when it fails,
sentry will not raise repeated notifications.
> Use cwd in twine upload command

- README.rst
- src/oca_github_bot/commands.py
- src/oca_github_bot/config.py
- src/oca_github_bot/tasks/__init__.py
- src/oca_github_bot/tasks/migration_issue_bot.py
- tests/cassettes/test_create_or_find_branch_milestone.yaml
- tests/cassettes/test_find_issue.yaml
- tests/cassettes/test_set_lines_issue.yaml
- tests/test_migration_issue_bot.py
New ocabot command for maintaining migration issues:
``/ocabot migration``, followed by the module name, performing the following:
* Look for an issue in that repository with the name "Migration to version  ``{version}``", where ``{version}`` is the name of the target branch.
* Add or edit a line in that issue, linking the module to the pull request  (PR) and the author of it.
* TODO: When the PR is merged, the line gets ticked.
* Put the milestone corresponding to the target branch in the PR.
cc @Tecnativa TT21199
> [ADD] ocabot migration issue maintainer

- src/oca_github_bot/tasks/migration_issue_bot.py
- Don't replace only on the start of the string. This can lead to multiple matches on modules starting with the same name. Although the rest of the added code now avoid to make more than one replacement, it's good to still do the exact match. This is provided through a regular expression matching the module name + space or the end of the line.
- Provide line filling shortcut for faster completion.
- Preserve possible existing mark check.
@Tecnativa
> [FIX] migration_issue_bot: String replacements fine tuning

- src/oca_github_bot/tasks/migration_issue_bot.py
This commit includes 2 fixes:
- Add to the regular expression that detects the line the carrier return (\r), as `$` is not representing the same as it's fed from the issue text.
- For detecting if the module list has ended, we were not taking into account that there can be modules already migrated, and thus, the `x` should be included in such regular expression.
@Tecnativa
> [FIX] migration_issue_bot: Line ending + already checked marks

- src/oca_github_bot/tasks/merge_bot.py
- src/oca_github_bot/tasks/migration_issue_bot.py
- src/oca_github_bot/tasks/rebase_bot.py
- src/oca_github_bot/utils.py
- tests/test_utils.py
Writing github bots is hard.
We happen to be leaking a secret. Example here: https://github.com/OCA/maintenance/pull/157#issuecomment-981837484
This explains why our GitHub token was revoked.
> Hide secrets when commenting on PRs

- src/oca_github_bot/tasks/mention_maintainer.py
- src/oca_github_bot/webhooks/on_pr_open_mention_maintainer.py
> Fix mention maintainers

- newsfragments/177.bugfix
- src/oca_github_bot/github.py
- src/oca_github_bot/utils.py
- tests/test_utils.py
- tox.ini
git fetch --prune --force fails when concurrent tasks
attempt to do it. Try to duck the issue and reduce sentry alerts
pollution by retrying automatically.
> Retry on git fetch errors

- newsfragments/178.bugfix
- src/oca_github_bot/tasks/merge_bot.py
This avoids some error noise in case branches have been deleted
before status webhooks are invoked or before the task has a chance
to run.
> Ignore BranchNotFoundError in merge status task

- environment.sample
Trivial fix.
**Step to reproduce :** 
- install the oca-github-bot
- create an ``environment`` file based on the ``environment.sample`` file.
- run docker-compose up --build
**Result**
```
ERROR: In file /home/user/grap_dev/grap-ocabot-env/src/oca-github-bot/environment: environment variable name '('https://pypi.org/simple', 'https://upload.pypi.org/legacy/', 'pypiuser', 'pypipassword'),' may not contain whitespace.
```
> [FIX] environment.sample : remove space that make build failing

- environment.sample
- newsfragments/183.bugfix
- src/oca_github_bot/config.py
- src/oca_github_bot/manifest.py
- src/oca_github_bot/tasks/mention_maintainer.py
- src/oca_github_bot/tasks/merge_bot.py
- tests/test_manifest.py
- tests/test_mention_maintainer.py
Search for maintainers in all the branches, to make possible maintainer to merge migration PRs. (#122)
Note, it works also for the past. (If i'm declared as maintainers of a 12.0 module, I will also have the possibility to merge PR against 8.0 (for backport / fixes / etc...)
**Deployment Note**
Once deployed, you should update your ``environment`` file. if not, the feature will be simply anavailable.
> [IMP] Search addons maintainers in other branches. Fix : #122

- newsfragments/190.bugfix
- src/oca_github_bot/tasks/migration_issue_bot.py
- tests/test_migration_issue_bot.py
Hi.
when calling ``/ocabot migration``, if the issue doesn't contains lines, the command fail silently. (that is due to the github api I guess. If we "edit" an github issue, and write the same text as before, the write is ignored).
with that patch, the line is added at the end of the migration issue body.
**Context** 
- can be used on custom modules, if we don't want to initialize the repository.
- usefull also in the Openupgrade project (See : https://github.com/OCA/OpenUpgrade/issues/3288#issuecomment-1157036504 
with the decision to not populate migration issue).
CC : @pedrobaeza, @sbidoul 
thanks for your review.
> [IMP] make _set_lines_issue working on empty issue

- newsfragments/191.feature
- src/oca_github_bot/tasks/migration_issue_bot.py
- tests/test_migration_issue_bot.py
**Use case**
- When maintainers are calling ``ocabot migration`` 
- if previous PR was present, 
**Current behaviour** 
The line of the migration issue is replaced silently by the new PR. (and new author).
However, in many cases, it is a duplication of work.
**Current workaround**
Maintainers should take a look on the migration issue, to check if an existing PR still exist and alert on the PR. See for exemple : https://github.com/OCA/OpenUpgrade/pull/3334#issuecomment-1164117298
For repos with a large amount of modules, it is very complicated to remember that a porting is already in progress.
**With that PR**
If an existing PR is referenced in the migration issue, a message is added to the new PR by the bot, referencing the first PR and pinging the original author.
CC : 
- @sbidoul 
- …
> [ADD] add warning in ocabot migration if previous PR was present for the same module

- pytest.ini
- src/oca_github_bot/build_wheels.py
- src/oca_github_bot/config.py
- src/oca_github_bot/manifest.py
- tests/test_build_wheels.py
- reuse the build environment for performance (and stability if/when we pin build tools versions)
- support (and give priority to) `pyproject.toml` in addon directories, towards removing the `setup` directories
TODO
> Refactor wheel builder

- src/oca_github_bot/tasks/migration_issue_bot.py
- tests/test_migration_issue_bot.py
> [FIX] ocabot migration duplicating lines in migration issue?

- newsfragments/192.bugfix
- src/oca_github_bot/tasks/merge_bot.py
- src/oca_github_bot/tasks/migration_issue_bot.py
- tests/test_migration_issue_bot.py
**Rational**
When maintainers are merging migration PR, they have to manually go to the according migration issue, and check the according line.
This operation is sometimes forgotten, and could be automated. 
This PR introduces that feature.
Fix : #189 
Discussion reference : https://github.com/OCA/OpenUpgrade/issues/3288#issuecomment-1157007829
CC : @sbidoul, @pedrobaeza 
Tested with ngrox : See edited migration issue by the bot here : https://github.com/grap-org-test-bot/github-ocabot-test/issues/27 (1 July 2022 17h46)
> [IMP] ocabot merge : check line in migration issue

- src/oca_github_bot/tasks/migration_issue_bot.py
Implementing #194.
Tried it in https://github.com/SirTakobi/l10n-italy/issues/9
> [IMP] not overwrite migration issue line unless the previous PR is closed

- src/oca_github_bot/tasks/migration_issue_bot.py
Blind commit. (not tested).
Should fix @pedrobaeza remarks https://github.com/OCA/oca-github-bot/pull/192#issuecomment-1596218816
CC : @sbidoul.
Don't understand how it could have worked in my test (https://github.com/grap-org-test-bot/github-ocabot-test/issues/27), but well !
> [FIX] _mark_migration_done_in_migration_issue : Call _find_issue with correct number of parameters

- .isort.cfg
- requirements-test.txt
- requirements.txt
- setup.py
- src/oca_github_bot/config.py
- src/oca_github_bot/version_branch.py
- tests/test_version_branch.py
At some point we will not want to continue generating READMEs and publishing wheels for older Odoo versions.
> Add option to set minimum supported branch

- src/oca_github_bot/tasks/merge_bot.py
We squash all post-merge commits done by the bot into one. 
This avoid the proliferation of not-very-useful commits that was recently made worse with the README generator that made an additional commit to update the README digest following the version bump.
> Squash post merge commits into one

- src/oca_github_bot/manifest.py
- src/oca_github_bot/tasks/merge_bot.py
- tests/common.py
- tests/conftest.py
- tests/test_build_wheels.py
- tests/test_git_push_if_needed.py
- tests/test_manifest.py
It will looks better if it have a tag.
> [IMP] Add the [BOT] tag to oca-github-bot commits

- Dockerfile
- setup.py
- src/oca_github_bot/config.py
- src/oca_github_bot/github.py
- src/oca_github_bot/tasks/main_branch_bot.py
- src/oca_github_bot/version_branch.py
- tests/test_git.py
- tests/test_version_branch.py
By default, this is done for branches 17.0+.
The minimum version to generate pyproject.toml instead of setup.py is configurable with `GEN_PYPROJECT_MIN_VERSION` and there are two new switchable tasks: `whool_init` and `gen_metapackage`.
> Generate pyproject.toml instead of setup.py

- newsfragments/270.bugfix
- src/oca_github_bot/build_wheels.py
Start build from an empty directory, to avoid accidentally importing python files from the addon root directory during the build process.
> Start wheel build from an empty directory

- src/oca_github_bot/build_wheels.py
This should fix https://github.com/OCA/rest-framework/pull/397#issuecomment-2301739586
> Don't prepend current directory when building

- src/oca_github_bot/tasks/merge_bot.py
We publish to PyPI before merging, because we don't want to merge if PyPI rejects the upload for any reason (such as ownership issues). There is a possibility that the upload succeeds and then the merge fails, but that should be  exceptional, and it is better than the contrary.
> Publish to PyPI immediately before pushing to main branch

- src/oca_github_bot/tasks/migration_issue_bot.py
Fix a small typo in the bot. 
See the message with the error here: https://github.com/OCA/account-financial-tools/pull/1980#issuecomment-2504836068
There is no space between "tobe"
> Fix a typo in multiline message

- Dockerfile
The icon generator will not overwrite existing icons, so there is no need to pin it.
The pinning was initially done out of fear an icon generator update would overwrite all icons at once.
> Simplify installation of oca-gen-addon-icon

- environment.sample
These releases are quite old, and modern ones are not taken into
consideration.
I know this is just a sample, but please take this chance to look at the
current bot production deployment, to see if this is misconfigured too.
@moduon MT-10479
> [FIX] Update other release branches
